### ISSUE TITLE
plugins crash on startup

### ISSUE THREAD

**Issue by jasonmadmax** [Ifera/ScoreHud#163] opened 2021-03-29 10:57 UTC
always crash on startup also when i remove all older version file or folder and add new version of the plugin
![Screenshot_20210329-144941_Chrome](https://user-images.githubusercontent.com/77657771/112827184-0dc2c480-909f-11eb-88e2-2fcd8064efdb.jpg)

**Comment by Ifera** [comment] 2021-04-01 22:22
Umm, please provide more details as I cannot reproduce this error. 
Don't delete the config file when the server is running. Always stop the sever, edit config and then run the server.
Further, make sure to delete the old ScoreHud folder in plugin_data directory when you run this plugin for the first time. 
Although it should update the configs all on its own but you could try doing this way also.
I am closing this issue since I couldnt reproduce it.
Until and unless you provide the steps to reproduce this issue, this issue will remain closed.

**Closed by Ifera** 2021-04-01 22:22 UTC

**Comment by jasonmadmax** [comment] 2021-04-03 17:46
i do everything but nothing
