### ISSUE TITLE
Problem with scorehud configuration

### ISSUE THREAD

**Issue by ivananaya12** [Ifera/ScoreHud#193] opened 2021-10-26 14:13 UTC
Sorry for making another one im not to good at this but I configured all of scorehud with the right tags and its still crashing but the crash dump doesn't seem to be scorehuds configuration but more in the code. Heres my crash dump link because I don't really understand it to much https://crash.pmmp.io/view/5365168

**Comment by Ifera** [comment] 2022-02-18 19:18
Closing this issue as the link to the crash dump is no longer valid.

Furthermore, I am optimistic that this should not occur in v7+ of ScoreHud as BasicScore has been integrated within ScoreHud and the majority of cases where this crash occurred involved BasicScore.

If this a crash caused by BasicScore then it could occur most probably when ScoreHud gets disabled for some reason. Anyways, like I mentioned, this should not occur anymore (hopefully). 

Please make an issue if it happens again.

**Closed by Ifera** 2022-02-18 19:18 UTC
Labels: bug, Status: Confirmed
